# Generated by Django 4.0.4 on 2022-05-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_country_lang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='anphoto',
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Язык'),
        ),
        migrations.DeleteModel(
            name='AnotherPhoto',
        ),
    ]
