# Generated by Django 4.0.4 on 2022-05-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_country_options_remove_country_anphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
    ]
