# Generated by Django 4.0.4 on 2022-05-15 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Религия'),
        ),
        migrations.CreateModel(
            name='CountryShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='country_shots/%Y/%m/%d/', verbose_name='Изображение')),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country', verbose_name='Страна')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.countryshots', verbose_name='Изображения'),
        ),
    ]
