# Generated by Django 4.0.4 on 2022-05-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_region_slug_alter_country_slug_alter_religion_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryshots',
            options={'verbose_name_plural': 'Country shots'},
        ),
    ]
