# Generated by Django 4.0.4 on 2022-05-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cityweather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityWeather',
        ),
    ]
