# Generated by Django 4.0.4 on 2022-05-31 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_country_images_alter_country_politic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryshots',
            name='country_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_name', to='app.country', verbose_name='Страна'),
        ),
    ]
