# Generated by Django 4.0.4 on 2022-07-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_countryshots_country_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
    ]
